[package]
name = "beacon_macros"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
cainome = { version = "0.10.0", features = ["abigen-rs"] }
cainome-cairo-serde = "0.4.0"
cairo_lang_reader = { git = "https://github.com/sai-starknet/cairo-lang-reader", branch = "main" }
cairo-lang-defs = "2.12.3"
cairo-lang-diagnostics = "2.12.3"
cairo-lang-filesystem = "2.12.3"
cairo-lang-macro = { version = "0.2.0", git = "https://github.com/software-mansion/scarb.git" }
cairo-lang-parser = "2.12.3"
cairo-lang-primitive-token = "1"
cairo-lang-syntax = "2.12.3"
cairo-lang-utils = "2.12.3"

convert_case = "0.8.0"
indoc = "2"
serde = { version = "1.0", features = ["derive"] }
smol_str = "0.2.2"
starknet = "0.17.0"
starknet-crypto = "0.8.1"
starknet-types-core = "0.2.1"
