[package]
cairo-version = "=2.9.2"
edition = "2024_07"
description = "The Dojo Beacon example"
name = "dojo_beacon_example"
version = "0.1.0"
experimental-features = ["negative_impls"]

[dependencies]
starknet = "=2.9.2"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.1" }
dojo_beacon = { path = "../" }
dojo_beacon_macros = { path = "../macros" }

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.1" }
cairo_test = "=2.9.2"

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"
