[package]
cairo-version = "=2.10.1"
edition = "2024_07"
description = "The Dojo Beacon example"
name = "example"
version = "0.1.0"
experimental-features = ["negative_impls"]

[dependencies]
starknet = "=2.10.1"
dojo_beacon = { path = "../" }

[dev-dependencies]
cairo_test = "=2.10.1"

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
allowed-libfuncs-list.name = "experimental"
