[package]
cairo-version = "2.11.4"
edition = "2024_07"
description = "The Torii Beacon fort interfacing with Torii"
name = "torii_beacon"
version = "1.6.0-rc.0"
experimental-features = ["negative_impls"]

[workspace]
members = ["macros"]

[dependencies]
starknet = "2.11.4"
dojo = { git = "https://github.com/dojoengine/dojo" }
dojo_macros = { git = "https://github.com/dojoengine/dojo" }
sai_core_utils = { git = "https://github.com/sai-starknet/cairo-utils", branch = "cairo-2.11.4" }
sai_access = { git = "https://github.com/sai-starknet/cairo-utils", branch = "cairo-2.11.4" }

[dev-dependencies]
cairo_test = "2.11.4"

[lib]

[[target.starknet-contract]]
sierra = true
allowed-libfuncs-list.name = "experimental"

[tool.fmt]
sort-module-level-items = true
