[workspace.package]
version = "1.7.0-rc.0"
edition = "2024_07"
cairo-version = "2.11.4"
scarb-version = "2.11.4"
description = "The Torii Beacon fort interfacing with Torii"
repository = "https://github.com/sai-starknet/torii-beacon"

[package]
name = "torii_beacon"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
description.workspace = true

[workspace]
members = ["macros", "packages/schema", "packages/library"]

[workspace.dependencies]
starknet = "2.11.4"
dojo = { git = "https://github.com/dojoengine/dojo" }
dojo_macros = { git = "https://github.com/dojoengine/dojo" }
sai_core_utils = { git = "https://github.com/sai-starknet/cairo-utils", branch = "cairo-2.11.4" }
sai_access = { git = "https://github.com/sai-starknet/cairo-utils", branch = "cairo-2.11.4" }

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]


[dev-dependencies]
cairo_test = "2.11.4"

[lib]

[tool]
fmt.workspace = true
scarb.workspace = true

[[target.starknet-contract]]
sierra = true
