[workspace.package]
version = "1.7.3"
edition = "2024_07"
cairo-version = "2.12.1"
scarb-version = "2.12.1"
description = "The Torii Beacon fort interfacing with Torii"
repository = "https://github.com/sai-starknet/torii-beacon"

[package]
name = "torii_beacon"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
description.workspace = true

[workspace]
members = [
    "macros",
    "packages/schema",
    "packages/library",
    "packages/component",
    "packages/dojo",
    "packages/macros",
    "packages/entity",
]

[workspace.dependencies]
starknet = "2.12.1"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.2" }
dojo_macros = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.2" }
sai_core_utils = { git = "https://github.com/sai-starknet/cairo-utils", tag = "v0.1.4" }
sai_access = { git = "https://github.com/sai-starknet/cairo-utils", tag = "v0.1.4" }
sai_address = { git = "https://github.com/sai-starknet/cairo-utils", tag = "v0.1.4" }

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[dependencies]
starknet = "2.12.1"
beacon_schema = { path = "packages/schema" }
beacon_library = { path = "packages/library" }
beacon_component = { path = "packages/component" }
dojo_beacon = { path = "packages/dojo" }
beacon_macros = { path = "packages/macros" }
beacon_entity = { path = "packages/entity" }

[dev-dependencies]
cairo_test = "2.12.1"

[lib]

[tool]
fmt.workspace = true
scarb.workspace = true

[[target.starknet-contract]]
sierra = true
