[package]
cairo-version = "=2.10.1"
edition = "2024_07"
description = "The Dojo Beacon fort interfacing with Torii"
name = "dojo_beacon"
version = "0.2.3"
experimental-features = ["negative_impls"]

[dependencies]
starknet = "2.10.1"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.6.0" }
sai_core_utils = { git = "https://github.com/sai-starknet/cairo-utils", tag = "cairo-2.10.1" }
sai_access = { git = "https://github.com/sai-starknet/cairo-utils", tag = "cairo-2.10.1" }

[dev-dependencies]
cairo_test = "2.10.1"

[lib]

[[target.starknet-contract]]
sierra = true
allowed-libfuncs-list.name = "experimental"

[tool.fmt]
sort-module-level-items = true
