[package]
cairo-version = "=2.10.1"
edition = "2024_07"
description = "The Dojo Beacon fort interfacing with Torii"
name = "dojo_beacon"
version = "0.2.3"
experimental-features = ["negative_impls"]

[dependencies]
starknet = "2.10.1"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.1" }


[dev-dependencies]
# dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.0" }
cairo_test = "2.10.1"

[lib]

[[target.starknet-contract]]
sierra = true
allowed-libfuncs-list.name = "experimental"
